" TODO	verify that on linux, the system and custom vimrc files are run

set nobackup	" disable automatic backups
set number		" enable line numbers
set nowrap		" disable line wrap

" set all tabbing to 4 characters wide and keep the tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

" set up some searching options
set incsearch
set hlsearch

" filetype functionality
filetype plugin on
filetype indent on

colorscheme vs2013dark

" set up the GUI
set guioptions-=g	" disable grayed out inactive menu items
set guioptions-=m	" disable the menu bar
set guioptions-=T	" disable the tool bar
set guioptions-=t	" disable tear off menus
set guioptions-=R	" disable the right hand scroll bar
set guioptions-=r	" disable the right hand scroll bar
set guioptions-=L	" disable the left hand scroll bar
set guioptions-=l	" disable the left hand scroll bar
set guifont=DejaVu\ Sans\ Mono\ 9

" map some handy fold commands. typing z# will fold & unfold everything to the
" #th fold. i only have 1-5 set, because i don't typically have more folds
" than that. z0 is not set because there is already zM.
nmap <unique> z1 :set foldlevel=1<CR>
nmap <unique> z2 :set foldlevel=2<CR>
nmap <unique> z3 :set foldlevel=3<CR>
nmap <unique> z4 :set foldlevel=4<CR>
nmap <unique> z5 :set foldlevel=5<CR>

" set up variables specific programming & markup languages
let html_use_w3_style = 1

